name: Release Docker Image for Forked Repo
on:
  workflow_call:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@1.16.0
        with:
          registry: ghcr.io
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ github.actor }}"
          password: " ${{ github.token }}"
