name: Release Docker Image (ubuntu-latest)
on:
  workflow_call:
    inputs:
      dockerfile_dir:
        description: The directory containing the Dockerfile to build
        default: "./"
        required: false
        type: string
      dockerfile_name:
        description: The name of the Dockerfile to build
        default: "Dockerfile"
        required: false
        type: string

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@1.17.2
        with:
          registry: ghcr.io
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ github.actor }}"
          password: " ${{ github.token }}"
          workdir: ${{ inputs.dockerfile_dir }}
          file: ${{ inputs.dockerfile_name }}
