name: Release Helm Chart

on:
  workflow_call:
    inputs:
      charts_dir:
        description: The directory containing Helm charts to release
        default: charts
        required: false
        type: string

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}
      chart_path: ${{ steps.list-changed.outputs.chart_path }}
    steps:
      - name: Setup Kube tools
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            yq
            helm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List changed charts
        id: list-changed
        run: |
          latest_tag=$( if ! git describe --tags --abbrev=0 2> /dev/null ; then git rev-list --max-parents=0 --first-parent HEAD ; fi )

          echo "Running: ct list-changed --since ${latest_tag} --target-branch ${{ github.ref_name }}"
          changed=$(ct list-changed --since "${latest_tag}" --target-branch "${{ github.ref_name }}")
          echo "${changed}"
          num_changed=$(wc -l <<< ${changed})
          if [[ "${num_changed}" -gt "1" ]] ; then
            echo "More than one chart changed, exiting"
            exit 1
          fi
          if [[ -n "${changed}" ]]; then
            name=$(yq ".name" < ${changed}/Chart.yaml)
            version=$(yq ".version" < ${changed}/Chart.yaml)
            tag_name="${name}-${version}"

            if [ $(git tag -l ${tag_name}) ]; then
              echo "Tag ${tag_name} already exists, skipping release"
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "Releasing ${changed}"
              echo "changed=true" >> $GITHUB_OUTPUT
              echo "chart_path=${changed}" >> $GITHUB_OUTPUT
            fi
          else
            echo "No charts have changed, skipping release"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  release:
    runs-on: self-hosted
    needs: [setup]
    permissions:
      contents: write
      packages: write
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Setup Kube tools
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            yq
            helm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Chart.yaml
        id: parse-chart
        run: |
          chart_path="${{ needs.setup.outputs.chart_path }}"
          name=$(yq ".name" < ${chart_path}/Chart.yaml)
          version=$(yq ".version" < ${chart_path}/Chart.yaml)
          description=$(yq ".description" < ${chart_path}/Chart.yaml)

          echo "chart_path=${chart_path}" >> $GITHUB_OUTPUT
          echo "chart_name=${name}" >> $GITHUB_OUTPUT
          echo "chart_version=${version}" >> $GITHUB_OUTPUT
          echo "chart_description=${description}" >> $GITHUB_OUTPUT
          echo "tag_name=${name}-${version}" >> $GITHUB_OUTPUT

      - name: Release chart to GitHub Container Registry
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          path: ${{ steps.parse-chart.outputs.chart_path }}
          name: ${{ steps.parse-chart.outputs.chart_name }}
          tag: ${{ steps.parse-chart.outputs.chart_version }}
          registry: ghcr.io
          repository: thealtoclef/helm-charts
          registry_username: ${{ github.actor }}
          registry_password: ${{ github.token }}
          update_dependencies: "true"

      - name: Make GitHub release
        uses: softprops/action-gh-release@v2.1.0
        with:
          body: |
            ${{ steps.parse-chart.outputs.chart_description }}

            Source commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          tag_name: ${{ steps.parse-chart.outputs.tag_name }}
