name: 🚀 Release Python package with Calendar Versioning
on:
  workflow_call:
    inputs:
      runs_on:
        description: The runner to use for the job
        default: "self-hosted"
        required: false
        type: string
      directory:
        description: Directory of the package
        type: string
        required: false
        default: "."
      setup_rust:
        description: Whether to setup rust
        type: boolean
        required: false
        default: false
      prerelease:
        description: Whether the release is a pre-release
        type: boolean
        required: false
        default: true
      publish:
        description: Whether to publish the package to the registry
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ${{ inputs.runs_on }}
    container: quay.io/pypa/manylinux_2_28_x86_64
    environment: pypi
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete trigger tag
        if: ${{ github.ref_type == 'tag' }}
        run: git push --delete origin ${{ github.event.ref }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Setup rust
        if: ${{ inputs.rustup }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Calendar Versioning (PEP 440 Compatible)
        id: calver
        uses: alepee/calendar-version-action@v1
        with:
          dateFormat: "YYYY0M.DD"
          format: "%NOW%.${{ inputs.prerelease && '0rc' || '' }}%MICRO%"

      - name: Git tag
        run: |
          git config --global --add safe.directory '*'
          git tag ${{ steps.calver.outputs.version }}

      - name: Build package
        run: |
          uv version ${{ steps.calver.outputs.version }} --directory ${{ inputs.directory }}
          uv build --directory ${{ inputs.directory }}

      - name: Publish package to registry
        if: ${{ inputs.publish == true }}
        run: uv publish --directory ${{ inputs.directory }}

      - name: Make GitHub release
        uses: softprops/action-gh-release@v2.1.0
        if: ${{ inputs.publish == true }}
        with:
          body: "**Source commit**: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          tag_name: ${{ steps.calver.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
