name: 🚀 Release Python package with Calendar Versioning
on:
  workflow_call:
    inputs:
      runs_on:
        description: The runner to use for the job
        default: "self-hosted"
        required: false
        type: string
      directory:
        description: Directory of the package
        type: string
        required: false
        default: "."
      prerelease:
        description: Whether the release is a pre-release
        type: boolean
        required: false
        default: true
      publish:
        description: Whether to publish the package to the registry
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ${{ inputs.runs_on }}
    container: ghcr.io/astral-sh/uv:debian
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global --add safe.directory '*'

      - name: Delete trigger tag
        if: ${{ github.ref_type == 'tag' }}
        run: git push --delete origin ${{ github.event.ref }}

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.thealtoclef.com
          role: reader
          method: jwt
          secrets: |
            secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
            secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;
            secret/data/ci npm_token

      - name: Setup system packages
        run: |
          apt-get update -y && apt-get install -y --no-install-recommends \
            libclang-dev \
            llvm-dev \
            libclang-15-dev \
            clang \
            libkrb5-dev

      - name: Calendar Versioning (PEP 440 Compatible)
        id: calver
        uses: alepee/calendar-version-action@v1
        with:
          dateFormat: "YYYY0M.DD"
          format: "%NOW%.${{ inputs.prerelease && '0rc' || '' }}%MICRO%"

      - name: Build package
        env:
          LIBCLANG_PATH: /usr/lib/llvm-15/lib
        run: |
          uv version ${{ steps.calver.outputs.version }} --directory ${{ inputs.directory }}
          uv build --directory ${{ inputs.directory }}

      - name: Publish package to registry
        if: ${{ inputs.publish == true }}
        run: uv publish --directory ${{ inputs.directory }}

      - name: Make GitHub release
        uses: softprops/action-gh-release@v2.1.0
        if: ${{ inputs.publish == true }}
        with:
          body: "**Source commit**: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          tag_name: ${{ steps.calver.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
